title: Amit Kumar
author: Amit Kumar
email: amitasviper@gmail.com
url: https://amitasviper.com
description: > # this means to ignore newlines until "baseurl:"
  
# social links
#twitter_username: amitasviper
github_username:  amitasviper
#rss: rss
#dribbble_username: jekyll
facebook_username: amitasviper
#flickr_username: jekyll
#instagram_username: amitasviper
linkedin_username: amitasviper
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: amitasviper
google_analytics: UA-115372554-1

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

disqus:
  shortname: amitasviper-com

plugins:
  - jekyll-seo-tag

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
